branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: feature
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: revert
          release: minor
        - type: docs
          release: patch
        - type: style
          release: minor
        - type: chore
          release: minor
        - type: refactor
          release: patch
        - type: deps
          release: minor
        - type: deps
          scope: internal
          release: false
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
            hidden: false
          - type: feature
            section: Features
            hidden: false
          - type: fix
            section: Bug Fixes
            hidden: false
          - type: perf
            section: Performance Improvements
            hidden: false
          - type: revert
            section: Reverts
            hidden: false
          - type: docs
            section: Documentation
            hidden: false
          - type: style
            section: Styles
            hidden: false
          - type: chore
            section: Chores
            hidden: false
          - type: deps
            section: Dependency Updates
            hidden: false
          - type: deps
            scope: internal
            hidden: true
          - type: refactor
            section: Refactoring
            hidden: false
          - type: test
            section: Tests
            hidden: false
          - type: build
            section: Build System
            hidden: false
          - type: ci
            section: Continuous Integration
            hidden: false
  - - "@semantic-release/github"
    - releasedLabels: false
tagFormat: ${version}
